### ISSUE TITLE
Update 'Production Operation' docs to acknowledge `configstore` Dynamic Configuration

### ISSUE THREAD

**Issue by charlese-instaclustr** [uber/Cadence-Docs#137]
Currently, https://cadenceworkflow.io/docs/operation-guide/setup/ only acknowledges the existence of (and explains) the file-based dynamic config option for Cadence. `configstore` Dynamic Config has been implemented and may be a preferable option for some Cadence users; however, the documentation is not advertising the fact that this option is available, or helping users to set it up.

We should update:
- https://cadenceworkflow.io/docs/operation-guide/setup/#static-configuration to show that the static configuration can be set to make Cadence use the `configstore` dynamic config implementation
- https://cadenceworkflow.io/docs/operation-guide/setup/#dynamic-configuration with directions for using the `configstore` implementation (i.e. setting, getting, updating values via the CLI)

**Comment by ibarrajo** [comment]
Thank you for adding the documentation!

**Comment by justinweng-instaclustr** [comment]
Hey @ibarrajo , my previous [PR](https://github.com/uber/Cadence-Docs/pull/144) for adding instructions on using `configstore` was accidentally closed without being merged due to me deleting the head repo. Therefore this task has not been completed. I've opened a new [PR](https://github.com/uber/Cadence-Docs/pull/178) for it. Is there any chance that I can get the new PR reviewed? Thanks.
