### ISSUE TITLE
Broken link on Concepts>Introduction

### ISSUE THREAD

**Issue by Sequoia** [uber/cadence-docs#56]
Where: https://cadenceworkflow.io/docs/concepts/

> The [deployment topology](https://cadenceworkflow.io/docs/concepts/topology/) explains how all these concepts are mapped to deployable software components.

This link 404s https://cadenceworkflow.io/docs/concepts/topology/

**Comment by longquanzheng** [comment]
Really? It works for me 🤔

**Comment by just-at-uber** [comment]
Ok, I think I know what the problem is here:
- If you open in a new window, it will show a 404 page as it navigates to a different URL (https://cadenceworkflow.io/docs/03-concepts/05-topology/)
- If you simply click it, it will navigate to the correct page (https://cadenceworkflow.io/docs/concepts/topology/)

I'll have a look and see if there is something that can be done to use the correct link here.
Thanks for the report @Sequoia

**Comment by just-at-uber** [comment]
Looks like this is a limitation on VuePress with an open issue describing the exact issue:
https://github.com/vuejs/vuepress/issues/1803

I will try implementing the hacky workaround to see if it fixes the issue. If not, I may need to keep this issue open until VuePress team makes a fix.

**Comment by just-at-uber** [comment]
Tested the same steps as before on cadenceworkflow.io and looks like the page is no longer redirecting to a 404 page. 

Thanks for the report @Sequoia !
